### ISSUE TITLE
Uncaught SyntaxError: Unexpected token (107:4)

### ISSUE THREAD

**Issue by eranimo** [stuart-williams/relative-require#18]
Had the following error when using with Atom 1.10.1

/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:2223

```
SyntaxError: Unexpected token (107:4)
    at Parser.pp$4.raise (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseBlock (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$1.parseFunction (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:1065:10)
    at Parser.pp$1.parseFunctionStatement (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:818:17)
    at Parser.pp$1.parseStatement (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:694:19)
    at Parser.pp$1.parseTopLevel (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/admin/.atom/packages/relative-require/node_modules/acorn/dist/acorn.js:3098:39)
    at exports.default (/Users/admin/.atom/packages/relative-require/lib/analyse-source.js:15:21)
    at atom-workspace.menuRequire (/Users/admin/.atom/packages/relative-require/lib/main.js:36:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1115:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:342:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)
```

**Comment by stuart-williams** [comment]
This is probibly a syntax error in your code. Acorn will throw an error when parsing if it encounters a syntax error

**Comment by petridw** [comment]
I'm working w Electron and get a similar syntax error when using this inside an html file. Is the reason you need to parse the code just to determine the line to insert the require statement on? What if you just add the require statement on the line that the cursor is on?
(edit: I see that you need to parse the current file in order to determine require/import syntax. Maybe just attempt to parse it, catch the parse error, and fall back to a default of require syntax if parsing fails?)

**Comment by stuart-williams** [comment]
Thanks for the feedback. Yes that's right, it parses to determine the import syntax and the cursor position of the last import statement. I think your suggestion is good, if the parser throws fallback to default. I'll look into patching this ASAP

**Comment by petridw** [comment]
Just wanted to say new version works great! Thanks for fixing that.
